/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import personLibrary.*;
import dateLibrary.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class validateInterface extends javax.swing.JFrame {

    /**
     * Creates new form validateInterface
     */
    public validateInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fldMSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fldFSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fldPhoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fldState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fldCURP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fldDay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fldMonth = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fldYear = new javax.swing.JTextField();
        btnValidateCurp = new javax.swing.JButton();
        sizer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Lato Semibold", 1, 24)); // NOI18N
        title.setText("Validación de CURP");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 30));

        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(fldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 190, -1));

        jLabel3.setText("Apellido materno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(fldMSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 140, -1));

        jLabel4.setText("Apellido paterno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        getContentPane().add(fldFSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));

        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        cbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexActionPerformed(evt);
            }
        });
        getContentPane().add(cbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("Datos de nacimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, -1));

        jLabel7.setText("Número de teléfono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        fldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldPhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(fldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 110, -1));

        jLabel8.setText("Estado de nacimiento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        getContentPane().add(fldState, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, -1));

        jLabel10.setText("CURP: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));
        getContentPane().add(fldCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel11.setText("Información personal");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, -1));

        jLabel12.setText("Día de nacimiento");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        getContentPane().add(fldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 70, -1));

        jLabel13.setText("Mes de nacimiento");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));
        getContentPane().add(fldMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 80, -1));

        jLabel14.setText("Año de nacimiento");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));
        getContentPane().add(fldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 80, -1));

        btnValidateCurp.setText("Validar");
        btnValidateCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateCurpActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidateCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, -1));
        getContentPane().add(sizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 36, 16));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexActionPerformed

    }//GEN-LAST:event_cbSexActionPerformed

    private void fldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPhoneNumberActionPerformed

    private void btnValidateCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateCurpActionPerformed
        String curp = fldCURP.getText(), fSurname = fldFSurname.getText(), mSurname = fldMSurname.getText(), name = fldName.getText(),
               phoneNumber = fldPhoneNumber.getText(), state = fldState.getText();
        if(fldCURP.getText().equalsIgnoreCase("") || fldFSurname.getText().equalsIgnoreCase("") || fldMSurname.getText().equalsIgnoreCase("") || fldName.getText().equalsIgnoreCase("") ||
               fldPhoneNumber.getText().equalsIgnoreCase("") || fldState.getText().equalsIgnoreCase("") ){
            JFrame f = new JFrame();   
            JOptionPane.showMessageDialog(f, "Rellene todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
            char sex = (cbSex.getSelectedItem().toString()).charAt(0);
            try {
                Date dte = new Date(Integer.parseInt(fldDay.getText()), Integer.parseInt(fldMonth.getText()), Integer.parseInt(fldYear.getText()));
                personValidations pV = new personValidations(curp, fSurname, mSurname, name, phoneNumber, state, dte, sex);
            } catch (Exception e) {
                JFrame f = new JFrame();   
                JOptionPane.showMessageDialog(f, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnValidateCurpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(validateInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(validateInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(validateInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(validateInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new validateInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidateCurp;
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JTextField fldCURP;
    private javax.swing.JTextField fldDay;
    private javax.swing.JTextField fldFSurname;
    private javax.swing.JTextField fldMSurname;
    private javax.swing.JTextField fldMonth;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldPhoneNumber;
    private javax.swing.JTextField fldState;
    private javax.swing.JTextField fldYear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel sizer;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
